HC = 'ghc'
OPTS = '--make -Wall -fno-warn-unused-do-bind'
if ENV['SRC']
  SRC = ENV['SRC']
  PROGRAM = SRC.sub /\.l?hs$/, ''
else
  PROGRAM = 'sum'
  SRC = PROGRAM + '.hs'
end

task :default => PROGRAM

file PROGRAM => SRC do|t|
  sh "#{HC} #{OPTS} #{t.source} -o #{t.name}"
end
