HC = 'ghc'
OPTS = ''
INSTALL_DIR = File.join ENV{"HOME"}, 'my', 'money'

if ENV['SRC']
  SRC = ENV['SRC']
  PROGRAM = SRC.sub /\.l?hs$/, ''
else
  PROGRAM = 'sum'
  SRC = PROGRAM + '.hs'
end

task :default => PROGRAM

file PROGRAM => SRC do|t|
  sh "#{HC} #{OPTS} #{t.source}"
end

task :install => PROGRAM do|t|
  mv t.source, INSTALL_DIR
end

task :run => :install do|t|
  sh "#{File.join INSTALL_DIR, PROGRAM} [0-9][0-9]/[0-9][0-9].txt [0-9][0-9]-[0-9][0-9].txt"
end
