HC = 'ghc'
OPTS = ''
INSTALL_ROOT = File.join ENV["HOME"], 'my', 'money'

INSTALL_DIRS = {
  "sum" => 'new',
}

if ENV['SRC']
  SRC = ENV['SRC']
  PROGRAM = SRC.sub /\.l?hs$/, ''
else
  PROGRAM = 'sum'
  SRC = PROGRAM + '.hs'
end

INSTALL_DIR = File.join INSTALL_ROOT, INSTALL_DIRS[PROGRAM].to_s

INSTALL_TO = File.join(
  INSTALL_DIR,
  PROGRAM + '.hs'
)

task :default => PROGRAM

file PROGRAM => SRC do|t|
  sh "#{HC} #{OPTS} #{SRC}"
end

task :install => PROGRAM do|t|
  mv PROGRAM, INSTALL_TO
end

task :run => :install do|t|
  Dir.chdir INSTALL_DIR
  sh "#{INSTALL_TO} [0-9][0-9]/[0-9][0-9].txt [0-9][0-9]-[0-9][0-9].txt > result.txt 2> err.txt"
end
